### ISSUE TITLE
showing nodes' movement in core in sdt3d went wrong

### ISSUE THREAD

**Issue by PengfeiM** [USNavalResearchLaboratory/sdt#24]
when I run a core sample with moving nodes, the nodes in sdt3d didn't move at all but the link is changed according to the links in core. 
However, when I move the nodes by hand, the node in sdt3d moved as well. 
Here is the error message on sdt3d command line 
![image](https://user-images.githubusercontent.com/45191163/103118094-546fdf80-46a8-11eb-9fc9-af418d6aa2cf.png)

**Comment by bharnden** [comment]
This is a CORE specific issue, which is fixed on develop and will be in next release.

This should be closed here.
