### ISSUE TITLE
URL connect timed out

### ISSUE THREAD

**Issue by JiasenLee** [USNavalResearchLaboratory/sdt#27]
When I ran ./sdt3d.sh, I met a problem as shown in the picture.When I browsed this website in the browser, 404 was displayed.

![time out](https://user-images.githubusercontent.com/24550544/112467349-ea97cc80-8da1-11eb-90e5-176a29c6b1c2.png)

**Comment by weston-nrl** [comment]
This was likely a temporary outage of the NASA website, which is used by the underlying NASA worldwind code for downloading the relevant imaging, etc.
